apps/category/urls.py
from django.urls import path
from .views import CategoriaListView, CategoriaCreateView, CategoriaUpdateView, CategoriaEliminarView

urlpatterns = [
    path('listar_categoria/',CategoriaListView.as_view(),name="listar-cat"),
    path('crear_categoria/',CategoriaCreateView.as_view(),name="crear-cat"),
    path('modificar_categoria/<int:pk>',CategoriaUpdateView.as_view(),name="modificar-cat"),
    path('eliminar_categoria/<int:pk>',CategoriaEliminarView.as_view(),name="eliminar-cat")
]

settings/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import include, path
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, re_path
import debug_toolbar

# from django.contrib.auth.views import (
#         login, 
#         logout_then_login, 
#         password_reset, 
#         password_reset_done, 
#         password_reset_confirm, 
#         password_reset_complete
#     )


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include(('apps.home.urls','index'),namespace='index')),
    re_path(r'^', include(('apps.category.urls','category'),namespace='category')),
    re_path(r'^', include(('apps.post.urls','post'),namespace='post')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns +=(
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    )

apps/category/models.py
from django.db import models

class Categoria(models.Model):
    
    name = models.CharField(
        max_length = 100,
        help_text = 'Nombre de Categoria'
    )
    
    slug = models.SlugField(
        max_length = 200
    )
    
    publish = models.BooleanField(
        default = True
    )
    
    def __str__(self):
        return self.name

apps/category/views.py
from django.urls import reverse
from django.utils import timezone
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Categoria
from django.contrib.messages.views import SuccessMessageMixin 

class CategoriaListView(ListView):

    model = Categoria
    paginate_by = 20
    
    def get_context_data(self, **kwargs):
        print("INGRESANDO A LA VISTA DE LISTAR CATEGORIAS")
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context
    
class CategoriaCreateView(SuccessMessageMixin, CreateView):
    model = Categoria # con que tabla se trabajara
    form = Categoria # crea el formulario del modelo
    template_name = 'category/crear_categoria.html' # renderizar en la plantilla
    fields = '__all__' # campos para el formulario
    success_message = 'CREADO' # Mostramos este Mensaje luego de Crear

    def get_success_url(self):        
        return reverse('category:listar-cat')
        
        
class CategoriaUpdateView(SuccessMessageMixin, UpdateView):
    model = Categoria # con que tabla se trabajara
    form = Categoria # crea el formulario del modelo
    template_name = 'category/modificar_categoria.html' # renderizar en la plantilla
    fields = '__all__' # campos para el formulario
    success_message = 'Modificado Correctamente !' # Mostramos este Mensaje luego de Crear

    def get_success_url(self):
        return reverse('category:listar-cat')

class CategoriaEliminarView(SuccessMessageMixin,DeleteView):
    model = Categoria
    form = Categoria
    fields = '__all__'
    template_name = 'category/eliminar_categoria.html'
    success_message = 'Eliminado Correctamente !' # Mostramos este Mensaje luego de Crear

    def get_success_url(self):
        return reverse('category:listar-cat')
    

apps/templates/category/categoria_list.html
{% extends "base_admin.html" %}

{% load static i18n %}

{% block title %} <title> Listado de Categoria </title> {% endblock title %}

{% block pushcss %}
    <link rel="stylesheet" type="text/css" href="{% static 'admin/toast/css/iziToast.min.css' %}" />
{% endblock pushcss %}

{% block content %}

{% if messages %}

<ul class="messages list-group mb-3">
    {% for message in messages %}
        {{ message }}
    {% comment %} <li{% if message.tags %} class="{{ message.tags }} list-group-item list-group-item-primary"{% endif %}>{{ message }}</li> {% endcomment %}
    {% endfor %}
</ul>
{% endif %}


<div class="page-title">
    <div class="row">
      <div class="col-sm-6">
        <h4 class="mb-0">Listado de Categorias </h4>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb pt-0 pe-0 float-start float-sm-end ">
          <li class="breadcrumb-item"><a href="#" class="default-color">Dashboard</a></li>
          <li class="breadcrumb-item active">Categorias </li>
        </ol>
      </div>

      <div class="card card-statistics mb-30">
        <div class="card-body">
            <a class="button x-small" href="{% url 'category:crear-cat' %}">Crear Nueva Categoria</a>
        </div>
    </div>

    </div>
  </div>

  <div class="row">
    <div class="col-xl-12 mb-30">
      <div class="card card-statistics h-100">
        <div class="card-body">
          <div class="d-block d-md-flex justify-content-between">
          <div class="table-responsive mt-15">
            <table class="table center-aligned-table mb-0">
              <thead>
                <tr class="text-dark">
                  <th>id</th>
                  <th>Nombre</th>
                  <th>Slug</th>
                  <th>Estado</th>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>

                {% if object_list %}
                    {% for categoria in object_list %}
                        <tr>
                        <td>{{ categoria.id }}</td>
                        <td>{{ categoria.name|upper }}</td>
                        <td>{{ categoria.slug }}</td>
                        {% if categoria.publish == True %}
                            <td><label class="badge bg-success">ACTIVO</label></td>
                        {% else %}
                            <td><label class="badge bg-danger">INACTIVO</label></td>
                        {% endif %}
                        <td><a href="#" class="btn btn-outline-warning btn-sm">Editar</a></td>
                        <td><a href="#" class="btn btn-outline-danger btn-sm">Eliminar</a></td>
                        </tr>
                    {% endfor %}
                {% endif %}

              </tbody>
            </table>

            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        {% comment %} <a href="?page=1">&laquo; first</a> {% endcomment %}
                        <a href="?page=1" type="button" class="btn btn-primary btn-sm">&laquo; Primero</a>

                        {% comment %} <a href="?page={{ page_obj.previous_page_number }}">previous</a> {% endcomment %}
                        <a href="?page={{ page_obj.previous_page_number }}" type="button" class="btn btn-warning btn-sm">Anterior</a>

                    {% endif %}
            
                    <span class="current">
                        Pagina <strong> {{ page_obj.number }}</strong> de <strong> {{ page_obj.paginator.num_pages }}. </strong>
                    </span>
            
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}" type="button" class="btn btn-primary btn-sm">Siguiente</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}" type="button" class="btn btn-warning btn-sm">Ultimo</a>

                        {% comment %} <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a> {% endcomment %}
                    {% endif %}
                </span>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
  

{% endblock content%}

{% block pushjs %}
    <script src="{% static 'admin/toast/js/iziToast.min.js' %}"></script>

    {% if messages %}
        {% for message in messages %}
            {% comment %} {% if message == 'CREADO' %} {% endcomment %}
                <script>
                    iziToast.success({
                        position: 'center', 
                        title: 'OK',
                        transitionIn: 'flipInX',
                        timeout: 10000,
                        message: '{{ message|safe }}',
                    });            
                </script>
            {% comment %} {% endif %} {% endcomment %}
        {% endfor %}  
    {% endif %}

{% endblock pushjs %}
{% comment %} {% for categoria in object_list %}
    <span> {{ categoria.name }} 
        {% if categoria.publish == True %}
            <strong> Publico </strong>
        {% else %}
            <strong> No Publico </strong>
        {% endif%}
    </span> <br>
{% endfor %} {% endcomment %}
{% comment %} <ul>

    {% if messages %}
    <ul class="messages list-group mb-3">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }} list-group-item list-group-item-primary"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

{% for article in object_list %}
    <li>{{ article.status }} - {{ article.name }}</li>
{% empty %}
    {% for categoria in categorias %}
        <li>{{ categoria.status }} - {{ categoria.name }} 
            <a href="{% url 'categoria:modificar-registro' categoria.id %}">-> EDITAR</a>
            <a href="{% url 'categoria:eliminar-registro' categoria.id %}">-> ELIMINAR</a>
        </li>
    {% endfor %}

{% endfor %}
</ul> {% endcomment %}

apps/templates/category/crear_categoria.html
{% extends "base_admin.html" %}

{% load static i18n %}

{% block title %} <title> Listado de Categoria </title> {% endblock title %}

{% block content %}

<div class="card card-statistics mb-30">
    <div class="card-body">
      <h5 class="card-title">Crear Categoria</h5>

      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardar</button>

        {% comment %} <input type="submit" value="GUARDAR"> {% endcomment %}
    </form>

      {% comment %} <form>
        <div class="mb-3">
          <label class="form-label" for="exampleInputEmail1">Email address</label>
          <input type="email" class="form-control" aria-describedby="emailHelp" placeholder="Enter email">
          <small class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="mb-3">
          <label class="form-label" for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" placeholder="Password">
        </div>
        <div class="form-check mb-3">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form> {% endcomment %}
    </div>
  </div>



{% endblock content %}

apps/templates/category/eliminar_categoria.html
<form method="post">{% csrf_token %}
    <p>Eliminar .... "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

apps/templates/category/modificar_categoria.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>