apps/home/urls.py
from django.urls import path
from .views import HomeView, LandingView,BlogView, BlogDetailView, ContactView ,PostView, PostDetailView

urlpatterns = [
    path('', LandingView.as_view(), name='view-landing'),
    path('dashboard/', HomeView.as_view(), name='view-dashboard'),
    path('detalle-blog:<int:pk>/', BlogDetailView.as_view(), name='blog-detail'),
    path('blog/', BlogView.as_view(), name='view-blog'),
    path('publicaciones/', PostView.as_view(), name='view-post'),
    path('detalle-post:<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('contactos',ContactView.as_view(),name='view-contact'),
    
]   

apps/post/urls.py
from django.urls import path
from .views import PostListView, PostCreateView
# , PostCreateView, PostUpdateView, PostEliminarView
# listar, crear , modificar,eliminar, detalle
# c r u d 

urlpatterns = [
    path('listar_post/',PostListView.as_view(),name="listar-post"),
    path('crear_post/',PostCreateView.as_view(),name="crear-post"),
    # path('modificar_post/<int:pk>',PostUpdateView.as_view(),name="modificar-post"),
    # path('eliminar_post/<int:pk>',PostEliminarView.as_view(),name="eliminar-post")
]

settings/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import include, path
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, re_path
import debug_toolbar

# from django.contrib.auth.views import (
#         login, 
#         logout_then_login, 
#         password_reset, 
#         password_reset_done, 
#         password_reset_confirm, 
#         password_reset_complete
#     )


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include(('apps.home.urls','index'),namespace='index')),
    re_path(r'^', include(('apps.category.urls','category'),namespace='category')),
    re_path(r'^', include(('apps.post.urls','post'),namespace='post')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns +=(
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    )

apps/post/models.py
from django.db import models
from apps.category.models import Categoria

class Post(models.Model):
    title = models.CharField(
        max_length = 100
    )
    
    content = models.TextField(
        help_text = 'descripcion'
    )
    
    slug = models.SlugField(
        max_length = 100
    )
    
    category = models.ForeignKey(
        Categoria, 
        on_delete = models.CASCADE
    )
    
    publish = models.BooleanField(
        default = True
    )
    
    def __str__(self):
        return self.title

apps/post/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import TemplateView, View, ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin 

from .models import Post

class PostListView(ListView):
    template_name = 'post/listar_post.html'
    model = Post
    
class PostCreateView(SuccessMessageMixin,CreateView):
    model = Post
    form = Post
    fields = '__all__'
    template_name = 'post/crear_post.html'
    success_message = 'Post Creado Correctamente !' # Mostramos este Mensaje luego de Crear un Postre

    def get_success_url(self):        
        return reverse('post:listar-post')

apps/templates/frontend/blog.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %}<title>Blog</title> {% endblock title %}

{% block content %}

    <div class="breadcaump-area pt--400 pt_lg--300 pt_md--250 pt_sm--200 pb--100 bg_image--8 breadcaump-title-bar breadcaump-title-white">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcaump-inner text-center">
                        <h2 class="heading">Blog</h2>
                        <div class="breadcrumb-insite">
                            <ul class="core-breadcaump">
                                <li><a href="index.html">Inicio</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <main class="page-content">

        <div class="bk-blog-grid-area pt--70 pb--100 pt_md--80 pb_md--80 pb_sm--80 pt_sm--60 bg_color--5">
            <div class="container">

                <div class="row">
                    <div class="col-lg-8 col-md-12 col-12">
                        <div class="row">

                            {% for categoria in object_list %}
                                <div class="col-lg-6 col-md-6 col-sm-6 col-12 move-up wow mt--30">
                                    <div class="blog-grid">
                                        <div class="post-thumb">
                                            <a href="{% url 'index:blog-detail' categoria.id %}">
                                                <img src="{% static 'frontend/img/blog/blog-django.jpg' %}" alt="django">
                                            </a>
                                        </div>
                                        <div class="post-content">
                                            <div class="post-inner">
                                                <h5 class="heading heading-h5">
                                                    <a href="{% url 'index:blog-detail' categoria.id %}">
                                                        {{ categoria.name }}
                                                    </a>
                                                </h5>
                                                <div class="post-meta">
                                                    <div class="post-date">Blog Django</div>
                                                    <div class="post-category"><a href="{% url 'index:blog-detail' categoria.id %}">ver mas</a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}

                            <div class="col-lg-12">

                                <div class="pagination">
                                    <span class="step-links">
                                        {% if page_obj.has_previous %}
                                            <a href="?page=1">&laquo; first</a>
                                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                                        {% endif %}
                                
                                        <span class="current">
                                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                        </span>
                                
                                        {% if page_obj.has_next %}
                                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                                        {% endif %}
                                    </span>
                                </div>
                                
                                {% comment %} <div class="brook-pagination-wrapper text-center pt--80 pt_md--40 pt_sm--40">
                                    <ul class="brook-pagination">
                                        <li class="active"><a href="#">1</a></li>
                                        <li><a href="#">2</a></li>
                                        <li><a href="#"><i class="fa fa-angle-right"></i></a></li>
                                    </ul>
                                </div> {% endcomment %}
                            </div>

                        </div>
                    </div>

                    <div class="col-lg-4 col-md-12 col-12 mt_md--40 mt_sm--40 mt--30">
                        <div class="blog-sidebar-container">
                            <div class="blog-sidebar-wrapper">

                                <div class="bl-sidebar instagram mt--50 wow move-up">
                                    <h5 class="widget-title">Facebook</h5>
                                        <div class="fb-page" data-href="https://www.facebook.com/DevZone-1953319114910539/" data-tabs="timeline" data-width="1000" data-height="300" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/InsoBolivia/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/InsoBolivia/">INSO</a></blockquote></div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </main>

{% endblock content %}

{% block pushjs %}
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v3.3&appId=383264375339567&autoLogAppEvents=1"></script>
{% endblock pushjs %}

apps/templates/frontend/contacto.html
{% extends 'base.html' %}
{% block title %} <title> CONTACTOS </title> {% endblock title %}

{% block pushcss %}
    
{% endblock pushcss %}

{% block content %}

<div class="brook-breadcaump-area pt--300 pt_md--250 pt_sm--200 pb--300 pb_md--250 pb_sm--200 bg_image--130 breadcaump-title-bar breadcaump-title-white">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcaump-inner text-center">
                    <h2 class="heading heading-h2 font-60 text-white">Contact Us</h2>
                </div>
            </div>
        </div>
    </div>
</div>


<main class="page-content">

    <!-- Start Contact Area -->
    <div class="bk_contact_classic bg_color--1 ptb--160 ptb-md--80 ptb-sm--80">
        <div class="container">
            <div class="row">

                <!-- Start Single Slide -->
                <div class="col-lg-4 col-xl-4 col-md-6 col-12 col-sm-12 wow move-up">
                    <div class="classic-address text-center">
                        <h4 class="heading heading-h4">Visit our studio at</h4>
                        <div class="desc mt--15">
                            <p class="bk_pra line-height-2-22">2005 Stokes Isle Apt. 896, <br> Vacaville 10010, USA</p>
                        </div>
                    </div>
                </div>
                <!-- End Single Slide -->

                <!-- Start Single Slide -->
                <div class="col-lg-4 col-xl-4 col-md-6 col-12 col-sm-12 wow move-up mt_sm--40">
                    <div class="classic-address text-center">
                        <h4 class="heading heading-h4">Message us</h4>
                        <div class="desc mt--15">
                            <p class="bk_pra line-height-2-22">info@yourdomain.com <br> (+68) 120034509</p>
                        </div>
                    </div>
                </div>
                <!-- End Single Slide -->

                <!-- Start Single Slide -->
                <div class="col-lg-4 col-xl-4 col-md-6 col-12 col-sm-12 wow move-up mt_md--40 mt_sm--40">
                    <div class="classic-address text-center">
                        <h4 class="heading heading-h4">Follow us</h4>
                        <div class="desc mt--15">
                            <ul class="social-icon icon-solid-rounded icon-size-medium text-center move-up wow">
                                <li class="facebook"><a href="#" class="link" aria-label="Facebook"><i class="fab fa-facebook"></i></a></li>
                                <li class="twitter"><a href="#" class="link" aria-label="Twitter"><i class="fab fa-twitter"></i></a></li>
                                <li class="instagram"><a href="#" class="link" aria-label="Instagram"><i class="fab fa-instagram"></i></a></li>
                                <li class="dribbble"><a href="#" class="link" aria-label="Dribbble"><i class="fab fa-dribbble"></i></a></li>
                                <li class="pinterest"><a href="#" class="link" aria-label="Pinterest"><i class="fab fa-pinterest"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- End Single Slide -->

            </div>
        </div>
    </div>
    <!-- End Contact Area -->

    <!-- Start Contact Form  -->
    <div class="brook-contact-form-area ptb--150 ptb-md--80 ptb-sm--60 bg_color--5">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="brook-section-title text-center mb--40">
                        <h4 class="heading heading-h4">Send us a message</h4>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <div class="contact-form" >
                        <form id="contact-form" action="http://whizthemes.com/shohel/php/mail.php">
                            <div class="row">
                                <div class="col-lg-12">
                                    <input name="con_name" type="text" placeholder="Name *">
                                </div>

                                <div class="col-lg-12 mt--30">
                                    <input name="con_email" type="email" placeholder="Email *">
                                </div>

                                <div class="col-lg-12 mt--30">
                                    <input type="text" placeholder="Phone number">
                                </div>

                                <div class="col-lg-12 mt--30">
                                    <textarea name="con_message" placeholder="Your message"></textarea>
                                </div>

                                <div class="col-lg-12 mt--30">
                                    <input type="submit" value="Send message">
                                    <p class="form-messege"></p>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Contact Form  -->

    <!-- Start Call To Action -->
    <div class="brook-call-to-action bg_color--41 ptb--70">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-8 col-sm-8 col-12">
                    <div class="call-content text-center text-sm-start">
                        <h3 class="heading heading-h3 text-white">We’re motivated by the desire to achieve.</h3>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-4 col-12">
                    <div class="call-btn text-center text-sm-end mt_mobile--20">
                        <a class="brook-btn bk-btn-white text-theme btn-sd-size btn-rounded" href="#">Find out
                            more</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Call To Action -->

</main>
{% endblock content %}

{% block pushjs %}
    
{% endblock pushjs %}

apps/templates/frontend/detalle_blog.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %}<title>Detalle Blog</title> {% endblock title %}

{% block content %}

    <div class="breadcaump-area pt--400 pt_lg--300 pt_md--250 pt_sm--200 pb--100 bg_image--8 breadcaump-title-bar breadcaump-title-white">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcaump-inner text-center">
                        <h2 class="heading">Blog</h2>
                        <div class="breadcrumb-insite">
                            <ul class="core-breadcaump">
                                <li><a href="{% url 'index:view-landing' %}">Inicio</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <main class="page-content">

        <!-- Start Blog Details -->
        <div class="brook-blog-details-area bg_color--1 pt--90 pb--150">
            <div class="container">
                <div class="row">

                    <div class="col-lg-4 col-md-12 col-sm-12 col-12 mt_md--60 mt_sm--60 order-2 order-lg-1">
                        <!-- Start Sidebar Area -->
                        <div class="blog-sidebar-container">
                            <div class="blog-sidebar-wrapper">

                                <!-- Start Single Widget -->
                                <div class="bl-sidebar search">
                                    <h5 class="widget-title">Facebook</h5>
                                    <div class="fb-page" data-href="https://www.facebook.com/DevZone-1953319114910539/" data-tabs="timeline" data-width="1000" data-height="300" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/InsoBolivia/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/InsoBolivia/">INSO</a></blockquote></div>
                                </div>

                            </div>
                        </div>

                    </div>

                    <div class="col-lg-8 col-md-12 col-sm-12 col-12 order-1 order-lg-2">
                        <div class="blog-details-wrapper">
                            <article class="blog-post standard-post">
                                <!-- Start Header -->
                                <div class="header mb--40 text-center">
                                    <h3 class="heading heading-h3 font-32">{{ object.name }}</h3>
                                    <div class="post-meta mt--20">
                                        <div class="post-date">Django</div>
                                        <div class="post-category"><a href="#">{{ object.status }}</a></div>
                                    </div>
                                </div>
                                <!-- Start Thumbnail -->
                                <div class="thumbnail mb--60">
                                    <img class="w-100" src="{% static 'frontend/img/blog/blog-django.jpg' %}" alt="Multipurpose">
                                </div>
                                <!-- Start Content -->
                                <div class="content basic-dark2-line-1px pb--50 mb--35">

                                    <div class="bk-quote-content">
                                        <blockquote class="brook-quote move-up wow">
                                            <div class="quote-text">El poder de Django.</div>
                                        </blockquote>
                                    </div>
 
                                </div>


                            </article>

                            <div class="comments-wrapper">
                                <div class="inner">
                                    <h4 class="heading heading-h4">Comentario</h4>
                                    <div class="commnent-list-wrap mt--25">
                                        <div id="disqus_thread"></div>
                                    </div>
                                </div>
                            </div>


                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- End Blog Details -->

    </main>

{% endblock content %}

{% block pushjs %}
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v3.3&appId=383264375339567&autoLogAppEvents=1"></script>

<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
    /*
    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://devzone-2.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
{% endblock pushjs %}

apps/templates/frontend/detalle_post.html
{% extends 'base.html' %}
{% load static i18n %}

{% block meta %}
    <meta property="og:url" content="django project"/>
    <meta property="og:type"        content="Blog Django " />
    <meta property="og:title"       content="{{ object.title }}" />
    <meta property="og:description" content="projecto django del curso" />
    <meta property="og:image"       content="{% static 'frontend/img/blog/blog-django.jpg' %}" />
{% endblock meta %}

{% load static i18n %}
{% block title %}<title>Detalle Post</title> {% endblock title %}

{% block content %}

    <div class="breadcaump-area pt--400 pt_lg--300 pt_md--250 pt_sm--200 pb--100 bg_image--8 breadcaump-title-bar breadcaump-title-white">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcaump-inner text-center">
                        <h2 class="heading">Post</h2>
                        <div class="breadcrumb-insite">
                            <ul class="core-breadcaump">
                                <li><a href="{% url 'index:view-landing' %}">Inicio</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <main class="page-content">

        <!-- Start Blog Details -->
        <div class="brook-blog-details-area bg_color--1 pt--90 pb--150">
            <div class="container">
                <div class="row">

                    <div class="col-lg-4 col-md-12 col-sm-12 col-12 mt_md--60 mt_sm--60 order-2 order-lg-1">
                        <!-- Start Sidebar Area -->
                        <div class="blog-sidebar-container">
                            <div class="blog-sidebar-wrapper">

                                <!-- Start Single Widget -->
                                <div class="bl-sidebar search">
                                    <h5 class="widget-title">Facebook</h5>
                                    <div class="fb-page" data-href="https://www.facebook.com/incosbot" data-tabs="timeline" data-width="" data-height="" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/incosbot" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/incosbot">IncosBot</a></blockquote></div>
                                </div>

                            </div>
                        </div>

                    </div>

                    <div class="col-lg-8 col-md-12 col-sm-12 col-12 order-1 order-lg-2">
                        <div class="blog-details-wrapper">
                            <article class="blog-post standard-post">
                                <!-- Start Header -->
                                <div class="header mb--40 text-center">
                                    <h3 class="heading heading-h3 font-32">{{ object.title }}</h3>
                                    <div class="post-meta mt--20">
                                        <div class="post-date">Django</div>
                                        <div class="post-category"><a href="#">{{ object.status }}</a></div>
                                    </div>
                                </div>
                                <!-- Start Thumbnail -->
                                <div class="thumbnail mb--60">
                                    <img class="w-100" src="{% static 'frontend/img/blog/blog-django.jpg' %}" alt="Multipurpose">
                                </div>
                                <!-- Start Content -->
                                <div class="content basic-dark2-line-1px pb--50 mb--35">

                                    <div class="bk-quote-content">
                                        <blockquote class="brook-quote move-up wow">
                                            <div class="quote-text">{{ object.content }}</div>
                                        </blockquote>
                                    </div>
 
                                </div>


                            </article>

                            <div class="comments-wrapper">
                                <div class="inner">
                                    <h4 class="heading heading-h4">Comentario</h4>
                                    <div class="commnent-list-wrap mt--25">
                                        <div id="disqus_thread"></div>
                                    </div>
                                </div>
                            </div>


                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- End Blog Details -->

    </main>

{% endblock content %}

{% block pushjs %}
<div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v15.0&appId=383264375339567&autoLogAppEvents=1" nonce="8EsTTFYb"></script>
    <script>
        /**
        *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
        *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
        /*
        var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        };
        */
        (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://cursodjango.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
{% endblock pushjs %}

apps/templates/frontend/post.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %} 
    <title>Publicaciones</title>
{% endblock title %}

{% block pushcss %}
{% endblock pushcss %}

{% block content %}
<div class="breadcaump-area pt--260 pb--80 pt_md--200 pt_sm--150 bg_color--5 breadcaump-title-bar">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcaump-inner text-center">
                    <h1 class="heading heading-h1">Publicaciones Django</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<main class="page-content">

    <div class="blog-creative-area bg_color--5 pt--70 pb--100">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 pr--100 pr_lg--15 pr_md--15 pr_sm--15">
                    {% for post in object_list %}
                    <div class="creative-blog wow move-up">
                        <div class="blog-grid blog-creative">
                            <div class="post-thumb">
                                <a href="{% url 'index:post-detail' post.id %}">
                                    <img src="{% static 'frontend/img/blog/post.jpg' %}" alt="Multipurpose template">
                                </a>
                            </div>
                            <div class="post-content">
                                <div class="post-inner">
                                    <h4 class="heading heading-h4"><a href="{% url 'index:post-detail' post.id %}">
                                        {{ post.title }}
                                    </a></h4>
                                    <div class="post-meta">
                                        <div class="post-date">Django-Blog</div>
                                        <div class="post-category"><a href="#">Django</a></div>
                                    </div>
                                    <div class="desc pl--60 pl_md--20 pl_sm--10 mt--20">
                                        <p class="bk_pra">{{ post.content }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}


                </div>

                <div class="col-lg-4 pl--40 pl_lg--15 pl_md--15 pl_sm--15 mt_md--40 mt_sm--40">
                    <!-- Start Sidebar Area -->
                    <div class="blog-sidebar-container">
                        <div class="blog-sidebar-wrapper">

                            <!-- Start Single Widget -->
                            <div class="bl-sidebar search">
                                <h5 class="widget-title">Facebook</h5>
                                <div class="fb-page" data-href="https://www.facebook.com/incosbot" data-tabs="timeline" data-width="" data-height="" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/incosbot" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/incosbot">IncosBot</a></blockquote></div>
                            </div>
                            <!-- End Single Widget -->

                        </div>
                    </div>
                    <!-- End Sidebar Area -->
                </div>
            </div>
        </div>
    </div>
    <!-- End BLog Area -->


</main>
{% endblock content %}


{% block pushjs %}

<div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v15.0&appId=383264375339567&autoLogAppEvents=1" nonce="8EsTTFYb"></script>
{% endblock pushjs %}