apps/home/urls.py
from django.urls import path
from .views import HomeView, LandingView,BlogView, BlogDetailView, ContactView ,PostView, PostDetailView

urlpatterns = [
    path('', LandingView.as_view(), name='view-landing'),
    path('dashboard/', HomeView.as_view(), name='view-dashboard'),
    path('detalle-blog:<int:pk>/', BlogDetailView.as_view(), name='blog-detail'),
    path('blog/', BlogView.as_view(), name='view-blog'),
    path('publicaciones/', PostView.as_view(), name='view-post'),
    path('detalle-post:<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('contactos',ContactView.as_view(),name='view-contact'),
    
]   

settings/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import include, path
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, re_path
import debug_toolbar

# from django.contrib.auth.views import (
#         login, 
#         logout_then_login, 
#         password_reset, 
#         password_reset_done, 
#         password_reset_confirm, 
#         password_reset_complete
#     )


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include(('apps.home.urls','index'),namespace='index')),
    re_path(r'^', include(('apps.category.urls','category'),namespace='category')),
    re_path(r'^', include(('apps.post.urls','post'),namespace='post')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns +=(
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    )

apps/templates/partials/css.html
{% load staticfiles %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:200,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
<link rel="stylesheet" href="{% static 'css/animate.min.css' %}">     
<link rel="stylesheet" href="{% static 'css/sweetalert2.css' %}">     
<link rel="stylesheet" href="{% static 'css/sweetalert2.min.css' %}">

apps/templates/partials/footer.html
{% load static i18n %}

<div class="bk-footer-inner ptb--150 pt_sm--100">
    <div class="container">
        <div class="row">

            <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                <div class="footer-widget text-var--2">
                    <div class="logo">
                        <a href="index.html">
                            <img src="{% static 'frontend/img/logo/brook-white2.png' %}" alt="brook white">
                        </a>
                    </div>
                    <div class="footer-inner">
                        <p>Brook is a multi-purpose WordPress theme for big and small-sized businesses. Enjoy
                            the theme's original design, functional features & responsive layouts.</p>
                    </div>
                </div>
            </div>

            <div class="col-lg-2 offset-lg-1 col-md-6 col-sm-6 col-12 mt_mobile--40">
                <div class="footer-widget text-var--2 menu--about">
                    <h2 class="widgettitle">About us</h2>
                    <div class="footer-menu">
                        <ul class="ft-menu-list bk-hover">
                            <li><a href="about-us-01.html">About Us</a></li>
                            <li><a href="team.html">Team</a></li>
                            <li><a href="#">Career</a></li>
                            <li><a href="services-classic.html">Services</a></li>
                            <li><a href="contact.html">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-lg-2 col-md-4 col-sm-4 col-12 mt_md--40 mt_sm--40 mt_mobile--40">
                <div class="footer-widget text-var--2 menu--about">
                    <h2 class="widgettitle">Other links</h2>
                    <div class="footer-menu">
                        <ul class="ft-menu-list bk-hover">
                            <li><a href="about-us-01.html">About Us</a></li>
                            <li><a href="team.html">Team</a></li>
                            <li><a href="#">Career</a></li>
                            <li><a href="services-classic.html">Services</a></li>
                            <li><a href="contact.html">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-lg-2 col-md-4 col-sm-4 col-12 mt_md--40 mt_sm--40 mt_mobile--40">
                <div class="footer-widget text-var--2 menu--about">
                    <h2 class="widgettitle">Other links</h2>
                    <div class="footer-menu">
                        <ul class="ft-menu-list bk-hover">
                            <li><a href="about-us-01.html">About Us</a></li>
                            <li><a href="team.html">Team</a></li>
                            <li><a href="#">Career</a></li>
                            <li><a href="services-classic.html">Services</a></li>
                            <li><a href="contact.html">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-lg-2 col-md-4 col-sm-4 col-12 mt_md--40 mt_md--40 mt_sm--40">
                <div class="footer-widget text-var--2 menu--instagram">
                    <h2 class="widgettitle">Social</h2>

                    <div class="social-share social--transparent text-white padding-10">
                        <a href="#"><i class="fab fa-facebook"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                        <a href="#"><i class="fab fa-dribbble"></i></a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

apps/templates/partials/js.html
{% load staticfiles %}

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/plugins-jquery.js' %}"></script>

<script src="{% static 'js/vue.js' %}"></script>
<script src="{% static 'js/vue_resource.js' %}"></script>

<script>
    var plugin_path = '{% static 'js/' %}'
</script>

<script src="{% static 'js/jvectormap/jquery-jvectormap-2.0.3.min.js' %}"></script>
<script src="{% static 'js/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<script src="{% static 'js/jvectormap/jquery-jvectormap-init.js' %}"></script>
<script src="{% static 'js/chart-init.js' %}"></script>
<script src="{% static 'js/calendar.init.js' %}"></script>
<script src="{% static 'js/sparkline.init.js' %}"></script>
<script src="{% static 'js/morris.init.js' %}"></script>
<script src="{% static 'js/sweetalert2.min.js' %}"></script>
<script src="{% static 'js/datepicker.js' %}"></script>
<script src="{% static 'js/toastr.js' %}"></script>
<script src="{% static 'js/validation.js' %}"></script>
<script src="{% static 'js/lobilist.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

apps/templates/partials/nav.html
{% load static i18n %}
<nav class="page_nav">
    <ul class="mainmenu">

        <li class="lavel-1"><a href="{% url 'index:view-landing' %}"><span>INICIO</span></a></li>

        <li class="lavel-1"><a href="{% url 'index:view-blog' %}"><span>BLOG</span></a></li>

        <li class="lavel-1 with--drop slide-dropdown"><a href="#"><span>LIBROS</span></a>
            <ul class="dropdown__menu">
                <li><a href=""><span>AUTORES</span></a></li>
                <li><a href=""><span>PUBLICACIONES</span></a></li>
            </ul>
        </li>

        <li class="lavel-1"><a href="{% url 'index:view-contact' %}"><span>CONTACTOS</span></a></li>

    </ul>
</nav>

apps/templates/partials/slider.html
{% load static i18n %}

        <div class="brook-hero-nav-slider-area">
            <div class="brook-element-carousel slick-arrow-center slick-arrow-rounded lr-0"
            data-slick-options='{ 
            "slidesToShow": 1, 
            "slidesToScroll": 1, 
            "arrows": true, 
            "infinite": true,
            "dots": false,
            "prevArrow": {"buttonClass": "slick-btn slick-prev", "iconClass": "ion ion-ios-arrow-back" },
            "nextArrow": {"buttonClass": "slick-btn slick-next", "iconClass": "ion ion-ios-arrow-forward" }
        }'
        >

                    <div class="hero-item bg-image" data-bg="{% static 'frontend/img/slider/essential/essential1.webp' %}">
                        <div class="container">
                            <div class="row">
                                <div class="col-12">
    
                                    <div class="hero-content-3 left">
                                        <h3>We're here to level <br> up your online <br> presence.</h3>
                                        <h6>A Creative Agency like no other. </h6>
                                        <a class="brook-btn btn-sd-size space-between btn-essential btn" href="#">Learn More</a>
                                    </div>
    
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="hero-item bg-image" data-bg="{% static 'frontend/img/slider/essential/Sh.jpg' %}">
                        <div class="container">
                            <div class="row">
                                <div class="col-12">
    
                                    <div class="hero-content-3 left">
                                        <h3>We're here to level <br> up your online <br> presence.</h3>
                                        <h6>A Creative Agency like no other. </h6>
                                        <a class="brook-btn btn-sd-size space-between btn-essential btn" href="#">Learn More</a>
                                    </div>
    
                                </div>
                            </div>
                        </div>
                    </div>
    
                </div>
        </div>